apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-kv
spec:
  provider:
    vault:
      server: "http://openbao.p8.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: p8-app-secrets
          namespace: p8
          key: P8_KMS_VAULT_TOKEN
