apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: p8-app-secrets-eso
  namespace: p8
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-kv
    kind: ClusterSecretStore
  target:
    name: p8-app-secrets-eso
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: p8/app-secrets
