apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: p8-keda-pg-connection
  namespace: p8
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-kv
    kind: ClusterSecretStore
  target:
    name: p8-keda-pg-connection
    creationPolicy: Owner
  data:
    - secretKey: connection
      remoteRef:
        key: p8/keda-pg-connection
        property: connection
