apiVersion: v1
kind: Service
metadata:
  name: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: kms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: kms
  ports:
    - name: api
      port: 8200
      targetPort: api
      protocol: TCP
